#!/bin/bash

dvdoc '{
  "sample": "git-changed",
  "description": "List only changed files since ref of remote’s main branch"
}' $0 $@ && exit

main=$(app-config gitMain)
extgroup=$(app-config gitChangedExtGroup)

if [ -z "$main" ]
then
  main=master
fi

if [ "$extgroup" = "js" ]
then
  git show --diff-filter=AM --pretty="" --name-only $(git rev-list ^remotes/origin/$main HEAD) -- '*.js' '*.jsx' '*.ts' '*.tsx'
else
  git show --diff-filter=AM --pretty="" --name-only $(git rev-list ^remotes/origin/$main HEAD) -- '*.rb'
fi
