#!/bin/bash

BROWN='\033[0;33m'
NC='\033[0m' # No Color

color () {
  printf "${BROWN}${1}${NC}"
}

color "Interactive? "
read -r edit

if [ "$edit" = "y" ]
then
  options="-i"
else
  options=""
fi

git fetch
git rebase $options remotes/origin/$(app-config gitMain) --autosquash
